# Generated by Django 4.2.11 on 2025-09-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='obras/')),
            ],
        ),
    ]
