# Generated by Django 4.2.27 on 2025-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_remove_obra_ano_obra_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagem',
            field=models.ImageField(upload_to='media/galeria'),
        ),
    ]
