# Generated by Django 4.2.28 on 2026-02-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_obra_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Genero',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='descricao',
        ),
        migrations.AddField(
            model_name='obra',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='core.genero'),
        ),
    ]
