services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: galeria_vangogh
      POSTGRES_USER: jade
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - media_volume:/code/media
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: galeria_vangogh
      POSTGRES_USER: jade
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
  media_volume:
