services:
  db:
    image: postgres:16.11
    container_name: galeria_vincent_van_gogh-db-1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: galeria_vangogh_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5436:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - media_volume:/code/media
    ports:
      - "8001:8000"
    environment:
      POSTGRES_DB: galeria_vangogh_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      - db

volumes:
  postgres_data:
  media_volume:

